dxn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home import views
from order import views as OrderViews
from user import views as UserViews
urlpatterns = [
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
    path('shopcart/', OrderViews.shopcart, name='shopcart'),
    path('about/', views.aboutus, name='aboutus'),
    path('contact/', views.contactus, name='contactus'),
    path('post/', views.post, name='post'),
    path('post/<int:id>/', views.post_detail, name='post_detail'),
    path('lic/', views.lic, name='lic'),
    path('lic/<int:id>/', views.lic_detail, name='lic_detail'),
    path('search/', views.search, name='search'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('category/<int:id>/<slug:slug>', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('login/', UserViews.login_form, name='login_form'),
    path('logout/', UserViews.logout_func, name='logout_func'),
    path('signup/', UserViews.signup_form, name='signup_form'),
    path('faq/', UserViews.faq, name='faq'),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from order import views


urlpatterns = [
    path('', views.index, name='index'),
    path('addtoshopcart/<int:id>', views.addtoshopcart, name='addtoshopcart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('orderproduct/', views.orderproduct, name='orderproduct'),

]

order/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm

from product.models import Product


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title

    @property
    def price(self):
        return (self.product.price)

    @property
    def amount(self):
        return (self.quantity * self.product.price)

class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']


class Order(models.Model):
    STATUS = (
        ('New', 'Yangi'),
        ('Accepted', 'Qabul qilingan'),
        ('Preparing', 'Tayyorlanish'),
        ('OnShipping', 'Yetkazib berishga'),
        ('Completed', 'Tugallangan'),
        ('Cancelled', 'Bekor qilingan'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False)
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=255)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    total = models.FloatField()
    status = models.CharField(max_length=15, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=25)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.first_name

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'phone', 'city', 'country']

class OrderProduct(models.Model):
    STATUS = (
        ('New', 'Yangi'),
        ('Accepted', 'Qabul qilingan'),
        ('Cancelled', 'Bekor qilingan'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=15, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.title

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.utils.crypto import get_random_string

from order.models import ShopCart, ShopCartForm, OrderForm, Order, OrderProduct
from product.models import Category, Product, Images, Comment


# from user.models import UserProfile
from user.models import UserProfile


def index(request):
    return HttpResponse('Order Page')


# @login_required(login_url='login')  # Check login
def addtoshopcart(request, id):
    url = request.META.get('HTTP_REFERER')  # get last url
    current_user = request.user  # Access User Session information

    checkproduct = ShopCart.objects.filter(product_id=id)  # Check product in shopcart
    if checkproduct:
        control = 1  # The product is in the cart
    else:
        control = 0  # The product is not in the cart

    if request.method == 'POST':  # if there is a post
        form = ShopCartForm(request.POST)
        if form.is_valid():
            if control == 1:  # Update shopcart
                data = ShopCart.objects.get(product_id=id)
                data.quantity += form.cleaned_data['quantity']
                data.save()
            else:  # Insert to Shopcart
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                data.quantity = form.cleaned_data['quantity']
                data.save()
        messages.success(request, "Product added to ShopCart")
        return HttpResponseRedirect(url)
    else:  # if there is no post
        if control == 1:  # Update shopcart
            data = ShopCart.objects.get(product_id=id)
            data.quantity += 1
            data.save()  #
        else:  # Insert to shopcart
            data = ShopCart()  # model
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.save()  #
        messages.success(request, "Product added to ShopCart")
        return HttpResponseRedirect(url)


def shopcart(request):
    category = Category.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for rs in shopcart:
        total += rs.product.price * rs.quantity
    # return HttpResponse(str(total))
    context = {
        'shopcart': shopcart,
        'category': category,
        'total': total,

    }
    return render(request, 'shopcart.html', context)


@login_required(login_url='/login')  # check login
def deletefromcart(request, id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, "Your item deleted from Shop Cart!")
    return HttpResponseRedirect("/shopcart")


def orderproduct(request):
    category = Category.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    profile = UserProfile.objects.get(user_id=current_user.id)
    total_quantity = 0
    total = 0
    for rs in shopcart:
        total += rs.product.price * rs.quantity
        total_quantity += rs.quantity
    # return HttpResponse(str(total))

    if request.method == 'POST':  # if there is a post
        form = OrderForm(request.POST)
        if form.is_valid():

            data = Order()
            data.first_name = form.cleaned_data['first_name']  # get product quantity from form
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.total_quantity = total_quantity
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode = get_random_string(10).upper()  # random code
            data.code = ordercode
            data.save()

            # Move Shopcart items to Order Product items
            shopcart = ShopCart.objects.filter(user_id=current_user.id)
            for rs in shopcart:
                detail = OrderProduct()
                detail.order_id = data.id  # Order id
                detail.product_id = rs.product_id
                detail.user_id = current_user.id
                detail.quantity = rs.quantity
                detail.price = rs.product.price
                detail.amount = rs.amount
                detail.save()
                # Reduce quantity of sold product from Amount of Product
                product = Product.objects.get(id=rs.product_id)
                product.amount -= rs.quantity
                product.save()

            ShopCart.objects.filter(user_id=current_user.id).delete()
            request.session['cart_items'] = 0
            messages.success(request, "Your Order Has Been Completed! Thank you!")
            return render(request, 'ordercomplete.html', {'ordercode': ordercode, 'category': category})
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect("/order/orderproduct")

    form = OrderForm
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {
        'shopcart': shopcart,
        'category': category,
        'total': total,
        'profile': profile,
        'form': form,
    }

    return render(request, 'orderproduct.html', context)

order/templates/ordercomplete.html
{% extends 'homebase.html'%}
{% load static %}
{% block title %} Order Complete {% endblock %}
{% block description %}  {{ category.description }}{% endblock %}
{% block keywords %}  {{ category.keywords }}{% endblock %}

{% block sidebar %}{% include 'sidebar.html' %} {% endblock %}

{% block body %}
    	<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="/">Home</a></li>
				<li class="active"> Order Complete </li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">

                    <div class="col-md-12">
						<div class="order-summary clearfix">
							<div class="section-title">
								<h3 class="title">Order Completed</h3>
							</div>
                            <hr>
                            <h2>Dear {{ user.first_name }} {{ user.last_name }}</h2>
                            <hr>
                            <h3>Your order is completed</h3>
                            <h3>Order Code: {{ ordercode }}</h3>
                            <h3>Thank You!</h3>
                            <hr>


						</div>

					</div>

			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->


 {% endblock %}
{% block foot %}{% include 'footer.html' %} {% endblock %}

order/templates/orderproduct.html
{% extends 'homebase.html'%}
{% load static %}
{% block title %} Order Page {% endblock %}
{% block description %}  {{ category.description }}{% endblock %}
{% block keywords %}  {{ category.keywords }}{% endblock %}

{% block sidebar %}{% include 'sidebar.html' %} {% endblock %}

{% block body %}
    	<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="/">Home</a></li>
				<li class="active"> Order Page </li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div  class="row">
            <form action="" method="post" >
                {% csrf_token %}
                <div class="col-md-6">
                    <div class="billing-details">

                        <div class="section-title">
                            <h4 class="title">Shipping Details</h4>
                        </div>
                        <p><label for="id_first_name">First name:</label>
                            <input type="text" name="first_name" value="{{ user.first_name }}" class="input" maxlength="10" required id="id_first_name">
                        </p>
                        <p><label for="id_last_name">Last name:</label>
                            <input type="text" name="last_name" value="{{ user.last_name }}" class="input" maxlength="10" required id="id_last_name">
                        </p>
                        <p><label for="id_address">Address:</label>
                            <input type="text" name="address" value="{{ profile.address }}" class="input" maxlength="150" id="id_address">
                        </p>
                        <p><label for="id_phone">Phone:</label>
                            <input type="text" name="phone" value="{{ profile.phone }}" class="input" maxlength="20" id="id_phone">
                        </p>
                        <p><label for="id_city">City:</label>
                            <select name="city" class="input" id="id_city">
                                <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                <option value="Tashkent"> Tashkent </option>
                                <option value="Fergana"> Fergana </option>
                                <option value="Namangan"> Namangan </option>
                                <option value="Buxoro"> Buxoro </option>
                                <option value="Navoi"> Navoi </option>
                                <option value="Samarqand"> Samarqand </option>
                                <option value="Surkhandarya"> Surkhandarya </option>
                                <option value="Kashkadarya"> Kashkadarya </option>
                                <option value="Sirdarya"> Sirdarya </option>
                                <option value="Jizzakh"> Jizzakh </option>
                                <option value="Andijan"> Andijan </option>
                                <option value="Xorazm"> Xorazm </option>
                                <option value="Karakalpakistan"> Karakalpakistan </option>
                            </select>

                        </p>
                        <p><label for="id_country">Country:</label>
                            <input type="text" name="country" class="input" id="id_country" value="{{ profile.country }}">
                        </p>
                        <div class="pull-right">
                            <button type="submit" class="primary-btn">Complete Order</button>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="shiping-methods">
                        <div class="section-title">
                            <h4 class="title">Payment Information</h4>
                        </div>
                        <p><label for="id_first_name"> Total:</label>
                            <input type="text" name="total" class="input" readonly value="{{ total }} so'm">

                        </p>
                        <p><label for="id_credit_card"> Credit Card Holder:</label>
                            <input type="text" name="credit_card" class="input" readonly value=" ">

                        </p>
                        <p><label for="id_credit_card_number">Credit Card number:</label>
                            <input type="text" name="credit_card_number" class="input" readonly value="">

                        </p>
                        <p><label for="id_credit_card_exp_date"> Credit Card Exp Date:</label>
                            <input type="text" name="credit_card_exp_date" class="input" readonly value=" ">

                        </p>
                        <p><label for="id_credit_card_security_number"> Credit Card Security Number:</label>
                            <input type="text" name="total" class="input" readonly value=" ">

                        </p>



                    </div>
                </div>
            </form>
                    <div class="col-md-12">
						<div class="order-summary clearfix">
							<div class="section-title">
								<h3 class="title">Shopcart Product List</h3>
							</div>
							<table class="shopping-cart-table table">
								<thead>
									<tr>
										<th>Product</th>
										<th></th>
										<th class="text-center">Price</th>
										<th class="text-center">Quantity</th>
										<th class="text-center">Total</th>
									</tr>
								</thead>
								<tbody>
                                {% for rs in shopcart %}
									<tr>
										<td class="thumb"><img src="{{ rs.product.image.url }}" alt=""></td>
										<td class="details">
											<a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}">{{ rs.product}}</a>

										</td>
										<td class="price text-center"><strong>{{rs.product.price}}</strong><br></td>
                                        <td class="qty text-center"><strong>{{ rs.quantity }} </strong></td>
										<td class="total text-center"><strong class="primary-color">{{rs.amount}}</strong></td>
                                   </tr>
                                {% endfor %}

								</tbody>
								<tfoot>
									<tr>
										<th class="empty" colspan="3"></th>
										<th>SUBTOTAL</th>
										<th colspan="2" class="sub-total">{{ total }}</th>
									</tr>
									<tr>
										<th class="empty" colspan="3"></th>
										<th>SHIPING</th>
										<td colspan="2">Free Shipping</td>
									</tr>
									<tr>
										<th class="empty" colspan="3"></th>
										<th>TOTAL</th>
										<th colspan="2" class="total">{{total}}</th>
									</tr>
								</tfoot>
							</table>

						</div>

					</div>

			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->


 {% endblock %}
{% block foot %}{% include 'footer.html' %} {% endblock %}

order/templates/shopcart.html
{% extends 'homebase.html'%}
{% load static %}
{% block title %} Shop Cart {% endblock %}
{% block description %}  {{ category.description }}{% endblock %}
{% block keywords %}  {{ category.keywords }}{% endblock %}

{% block sidebar %}{% include 'sidebar.html' %} {% endblock %}

{% block body %}
    	<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="/">Home</a></li>
				<li class="active"> Shop Cart  </li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">

                    <div class="col-md-12">
						<div class="order-summary clearfix">
							<div class="section-title">
								<h3 class="title">Shopcart Product List</h3>
							</div>
							<table class="shopping-cart-table table">
								<thead>
									<tr>
										<th>Product</th>
										<th></th>
										<th class="text-center">Price</th>
										<th class="text-center">Quantity</th>
										<th class="text-center">Total</th>
										<th class="text-right"></th>
									</tr>
								</thead>
								<tbody>
                                {% for rs in shopcart %}
									<tr>
										<td class="thumb"><img src="{{ rs.product.image.url }}" alt=""></td>
										<td class="details">
											<a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}">{{ rs.product}}</a>

										</td>
										<td class="price text-center"><strong>{{rs.product.price}}</strong><br></td>
                                        <td class="qty text-center"><strong>{{ rs.quantity }} </strong></td>
										<td class="total text-center"><strong class="primary-color">{{rs.amount}}</strong></td>
                                        <td class="text-right"><a href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Delete! Are you sure?')" class="main-btn icon-btn"><i class="fa fa-close"></i></a></td>
									</tr>
                                {% endfor %}

								</tbody>
								<tfoot>


									<tr>
										<th class="empty" colspan="3"></th>
										<th>TOTAL</th>
										<th colspan="2" class="total">{{total}}</th>
									</tr>
								</tfoot>
							</table>
							<div class="pull-right">
								<a href="/order/orderproduct" class="primary-btn">Place Order</a>
							</div>
						</div>

					</div>

			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->


 {% endblock %}
{% block foot %}{% include 'footer.html' %} {% endblock %}